[package]
name = "per-route-middleware"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
rust-api = { path = "../.." }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
